# Generated by Django 3.2.6 on 2021-08-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Blogger',
        ),
    ]
